package commands

func RegisterCommands(r CommandRegistry) {
	RegisterPINGCommand(r)
	RegisterGetCommand(r)
	RegisterSetCommand(r)
	RegisterMSetCommand(r)
	RegisterDeleteCommand(r)
	RegisterScanKVSCommand(r)
	RegisterScanKeysCommand(r)
	RegisterDeletePrefixCommand(r)
	RegisterKeysCommand(r)
	RegisterKVSCommand(r)
	RegisterMGetCommand(r)
	RegisterDBSizeCommand(r)
	RegisterZAddCommand(r)
	RegisterZRangeLexCommand(r)
	RegisterZRangeLexKeysCommand(r)
	RegisterZRangeScoreCommand(r)
	RegisterZRangeScoreKVSCommand(r)
	RegisterZRemCommand(r)
	RegisterZScoreCommand(r)
	RegisterZCardCommand(r)
	RegisterZRevRangeScoreCommand(r)
	RegisterZRevRangeScoreKVSCommand(r)
	RegisterZRevRangeLexKeysCommand(r)
	RegisterZRevRangeLexKVSCommand(r)
	RegisterFlushAllCommand(r)
	RegisterLPushCommand(r)
	RegisterRPushCommand(r)
	RegisterLPopCommand(r)
	RegisterRPopCommand(r)
	RegisterLRemCommand(r)
	RegisterLSetCommand(r)
	RegisterLRangeCommand(r)
	RegisterLLenCommand(r)
	RegisterLIndexCommand(r)
}
